version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
