name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV
  
      - name: Install Dependencies
        run: |
             npm ci
             npm install pm2 -g 
        working-directory: server/


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Transfer Files and Deploy
        run: |
            sshpass -p '42FC#Tgd*Wesdxc' ssh -o StrictHostKeyChecking=no  ec2-user@44.201.127.74 "mkdir -p /app/backend"

            sshpass -p '42FC#Tgd*Wesdxc' scp -r Backend/* root@44.201.127.74:/app/backend/
            sshpass -p '42FC#Tgd*Wesdxc' scp -r Backend/.env.production ec2-user@44.201.127.74:/app/backend/
            sshpass -p '42FC#Tgd*Wesdxc' scp -r Backend/.env.development ec2-user@44.201.127.74:/app/backend/
            sshpass -p '42FC#Tgd*Wesdxc' ssh -o StrictHostKeyChecking=no ec2-user@44.201.127.74 "cd /app/backend && npm install && npm install pm2 --save-dev &&  npm install cross-env"
            sshpass -p '42FC#Tgd*Wesdxc' ssh -o StrictHostKeyChecking=no ec2-user@44.201.127.74 "cd /app/backend && NODE_ENV=production  pm2 restart backend" 
