name: "CI/CD Pipeline Frontend"

on:
    push:
        branches: 
            - main
    pull_request:
        branches:
            - main 
    workflow_dispatch:         

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3 
          with: 
            node-version: 20
            
        - name: Set NODE_ENV to production
          run: echo "NODE_ENV=production" >> $GITHUB_ENV

        - name: Install dependencies
          run: | 
            npm install
            npm install pm2 -g
          working-directory: frontendreact/        

  deploy: 
    needs: build
    runs-on: ubuntu-latest   
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up SSH
          run: |
            mkdir -p ~/.ssh
            echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H 44.201.127.74 >> ~/.ssh/known_hosts

        - name: Install dependencies on EC2
          run: |
            ssh -o StrictHostKeyChecking=no ec2-user@44.201.127.74 "sudo mkdir -p /app/frontend"
            scp -r frontendreact/* ec2-user@44.201.127.74:/app/frontend/

        - name: Install Node.js and Build on EC2
          run: |
            ssh -o StrictHostKeyChecking=no ec2-user@44.201.127.74 "
            cd /app/frontend &&
            npm install &&
            npm install -g serve &&
            npm run build
            "
